# Generated by Django 4.2.7 on 2025-07-06 13:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="品牌名稱")),
                ("description", models.TextField(blank=True, verbose_name="品牌描述")),
                ("logo_url", models.URLField(blank=True, verbose_name="品牌Logo")),
                ("website", models.URLField(blank=True, verbose_name="官網")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分類名稱")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL友好名稱"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "產品分類",
                "verbose_name_plural": "產品分類",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="產品名稱")),
                ("description", models.TextField(blank=True, verbose_name="產品描述")),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="商品編號"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="基礎售價",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="成本價格",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="重量(克)",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="尺寸(長x寬x高)"
                    ),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="產品圖片")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "is_digital",
                    models.BooleanField(default=False, verbose_name="是否為數位商品"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="稅率(%)",
                    ),
                ),
                (
                    "min_order_quantity",
                    models.PositiveIntegerField(default=1, verbose_name="最小訂購量"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="標籤"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.brand",
                        verbose_name="品牌",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                        verbose_name="產品分類",
                    ),
                ),
            ],
            options={
                "verbose_name": "產品",
                "verbose_name_plural": "產品",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="變體名稱")),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="變體商品編號"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="變體售價",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="變體成本",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(default=dict, verbose_name="屬性(顏色、尺寸等)"),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=50, verbose_name="條碼"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                        verbose_name="產品",
                    ),
                ),
            ],
            options={
                "verbose_name": "產品款式變體",
                "verbose_name_plural": "產品款式變體",
                "ordering": ["product", "name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="供應商名稱")),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="聯絡人"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="電子郵件"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="付款條件"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="信用額度",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "供應商",
                "verbose_name_plural": "供應商",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("inbound", "入庫"),
                            ("outbound", "出庫"),
                            ("adjustment", "調整"),
                            ("stocktake", "盤點"),
                        ],
                        max_length=20,
                        verbose_name="異動類型",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="異動數量")),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("order", "訂單"),
                            ("purchase", "採購"),
                            ("adjustment", "調整"),
                            ("stocktake", "盤點"),
                            ("return", "退貨"),
                        ],
                        max_length=20,
                        verbose_name="關聯類型",
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="關聯ID"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="異動時間"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                        verbose_name="產品",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.productvariant",
                        verbose_name="產品款式變體",
                    ),
                ),
            ],
            options={
                "verbose_name": "庫存異動記錄",
                "verbose_name_plural": "庫存異動記錄",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.supplier",
                verbose_name="供應商",
            ),
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="舊價格",
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="新價格",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(max_length=200, verbose_name="變動原因"),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                (
                    "created_by",
                    models.CharField(max_length=100, verbose_name="變更人員"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.product",
                        verbose_name="產品",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.productvariant",
                        verbose_name="產品款式變體",
                    ),
                ),
            ],
            options={
                "verbose_name": "價格歷史",
                "verbose_name_plural": "價格歷史",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.PositiveIntegerField(default=0, verbose_name="現有庫存"),
                ),
                (
                    "quantity_reserved",
                    models.PositiveIntegerField(default=0, verbose_name="已預留庫存"),
                ),
                (
                    "reorder_level",
                    models.PositiveIntegerField(default=10, verbose_name="再訂購點"),
                ),
                (
                    "max_stock_level",
                    models.PositiveIntegerField(default=1000, verbose_name="最大庫存"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="庫存位置"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="products.product",
                        verbose_name="產品",
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="products.productvariant",
                        verbose_name="產品款式變體",
                    ),
                ),
            ],
            options={
                "verbose_name": "庫存",
                "verbose_name_plural": "庫存",
            },
        ),
    ]
