# Generated by Django 4.2.7 on 2025-07-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='客戶年齡', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', '其他'), ('prefer_not_to_say', '不願透露')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_categories_interest',
            field=models.JSONField(blank=True, default=list, help_text='感興趣的產品類別'),
        ),
        migrations.AddField(
            model_name='customer',
            name='seasonal_purchase_pattern',
            field=models.CharField(blank=True, choices=[('spring', '春季購買'), ('summer', '夏季購買'), ('autumn', '秋季購買'), ('winter', '冬季購買'), ('year_round', '全年均勻')], help_text='季節性購買模式', max_length=20, null=True),
        ),
    ]
